# Generated by Django 3.2.9 on 2021-11-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.IntegerField()),
                ('usuario', models.IntegerField()),
                ('fecprestamo', models.DateField()),
                ('fecdevolucion', models.DateField()),
            ],
        ),
    ]
